version: '3.4'

services:
  catalogservice:
    image: abayomiganiy/catalogservice
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
